// merge-profil.js
// Rulează cu: node merge-profil.js
const fs = require("fs");
const path = require("path");

const DATA = {
ro: { profil: {
  loading: "Sincronizare Profil...",
  demoMode: "MOD VIZUALIZARE",
  idPrefix: "ID: ",
  defaultUser: "Utilizator Chronos",
  save: "Salvează",
  saving: "Așteaptă...",
  logout: "Deconectare",
  demoLogout: "Ieșire Demo",
  activeSubscription: "Abonament Activ",
  trialSuffix: "(TRIAL)",
  changeSubscriptionBtn: "Schimbă Abonamentul",
  fullNameLabel: "👤 Nume Complet",
  emailLabel: "✉️ Email",
  phoneLabel: "📱 Telefon",
  roleLabel: "💼 Rol / Funcție",
  publicLinkBadge: "Configurare Link Public",
  slugLabel: "🔗 ADRESA UNICĂ DE REZERVARE (SLUG)",
  slugPrefix: "/rezervare/",
  slugPlaceholder: "nume-afacere",
  reserveLinkBtn: "Rezervă Link Unic",
  checking: "Se verifică...",
  warningTitle: "⚠️ IMPORTANȚĂ MAXIMĂ (OBLIGATORIU):",
  warningText: "Această adresă (Slug) este identitatea ta digitală. Orice modificare a acestui link va invalida automat Codurile QR generate anterior și link-urile trimise deja clienților. Vă rugăm să alegeți un nume reprezentativ (ex: salon-art-nails) pe care să nu îl mai schimbați ulterior pentru a păstra conexiunea activă cu scanările clienților.",
  changePasswordBtn: "🔒 Schimbă parola de acces",
  passwordModalTitle: "Securitate",
  newPasswordPlaceholder: "PAROLĂ NOUĂ",
  confirmPasswordPlaceholder: "CONFIRMĂ PAROLA",
  profileUpdated: "✅ Profil actualizat!",
  saveErrorPrefix: "Eroare la salvare: ",
  slugMinLength: "⚠️ Adresa unică (slug) trebuie să aibă minim 3 caractere.",
  slugTaken: "❌ Eroare: Numele \"{slug}\" este deja rezervat de altcineva. Te rugăm să alegi o altă variantă.",
  slugSuccess: "✅ Felicitări! Adresa ta unică a fost rezervată cu succes.",
  errorPrefix: "Eroare: ",
  passwordMismatch: "Parolele nu coincid!",
  passwordUpdated: "✅ Parola actualizată!",
  avatarErrorPrefix: "Eroare avatar: ",
  demoDisabled: "🔒 Dezactivat în Demo.",
  changeAvatar: "Schimbă",
  plans: {
    free: { nume: "CHRONOS FREE", limita: "30 rezervări / lună" },
    pro: { nume: "CHRONOS PRO", limita: "150 rezervări / lună" },
    elite: { nume: "CHRONOS ELITE", limita: "500 rezervări / lună" },
    team: { nume: "CHRONOS TEAM", limita: "Rezervări nelimitate" }
  }
}},
en: { profil: {
  loading: "Syncing Profile...",
  demoMode: "PREVIEW MODE",
  idPrefix: "ID: ",
  defaultUser: "Chronos User",
  save: "Save",
  saving: "Please wait...",
  logout: "Log Out",
  demoLogout: "Exit Demo",
  activeSubscription: "Active Plan",
  trialSuffix: "(TRIAL)",
  changeSubscriptionBtn: "Change Plan",
  fullNameLabel: "👤 Full Name",
  emailLabel: "✉️ Email",
  phoneLabel: "📱 Phone",
  roleLabel: "💼 Role / Position",
  publicLinkBadge: "Public Link Setup",
  slugLabel: "🔗 UNIQUE BOOKING ADDRESS (SLUG)",
  slugPrefix: "/booking/",
  slugPlaceholder: "business-name",
  reserveLinkBtn: "Reserve Unique Link",
  checking: "Checking...",
  warningTitle: "⚠️ VERY IMPORTANT (REQUIRED):",
  warningText: "This address (Slug) is your digital identity. Any change to this link will automatically invalidate previously generated QR Codes and links already sent to clients. Please choose a representative name (e.g. salon-art-nails) that you won't change later, to keep the connection active with client scans.",
  changePasswordBtn: "🔒 Change access password",
  passwordModalTitle: "Security",
  newPasswordPlaceholder: "NEW PASSWORD",
  confirmPasswordPlaceholder: "CONFIRM PASSWORD",
  profileUpdated: "✅ Profile updated!",
  saveErrorPrefix: "Error saving: ",
  slugMinLength: "⚠️ The unique address (slug) must be at least 3 characters.",
  slugTaken: "❌ Error: The name \"{slug}\" is already reserved by someone else. Please choose another option.",
  slugSuccess: "✅ Congratulations! Your unique address has been reserved successfully.",
  errorPrefix: "Error: ",
  passwordMismatch: "Passwords don't match!",
  passwordUpdated: "✅ Password updated!",
  avatarErrorPrefix: "Avatar error: ",
  demoDisabled: "🔒 Disabled in Demo.",
  changeAvatar: "Change",
  plans: {
    free: { nume: "CHRONOS FREE", limita: "30 bookings / month" },
    pro: { nume: "CHRONOS PRO", limita: "150 bookings / month" },
    elite: { nume: "CHRONOS ELITE", limita: "500 bookings / month" },
    team: { nume: "CHRONOS TEAM", limita: "Unlimited bookings" }
  }
}},
fr: { profil: {
  loading: "Synchronisation du profil...",
  demoMode: "MODE APERÇU",
  idPrefix: "ID : ",
  defaultUser: "Utilisateur Chronos",
  save: "Enregistrer",
  saving: "Patientez...",
  logout: "Déconnexion",
  demoLogout: "Quitter la démo",
  activeSubscription: "Abonnement actif",
  trialSuffix: "(ESSAI)",
  changeSubscriptionBtn: "Changer d'abonnement",
  fullNameLabel: "👤 Nom complet",
  emailLabel: "✉️ Email",
  phoneLabel: "📱 Téléphone",
  roleLabel: "💼 Rôle / Fonction",
  publicLinkBadge: "Configuration du lien public",
  slugLabel: "🔗 ADRESSE UNIQUE DE RÉSERVATION (SLUG)",
  slugPrefix: "/reservation/",
  slugPlaceholder: "nom-entreprise",
  reserveLinkBtn: "Réserver le lien unique",
  checking: "Vérification...",
  warningTitle: "⚠️ TRÈS IMPORTANT (OBLIGATOIRE) :",
  warningText: "Cette adresse (Slug) est ton identité numérique. Toute modification de ce lien invalidera automatiquement les codes QR déjà générés et les liens déjà envoyés aux clients. Choisis un nom représentatif (ex : salon-art-nails) que tu ne changeras plus, pour garder la connexion active avec les scans clients.",
  changePasswordBtn: "🔒 Changer le mot de passe",
  passwordModalTitle: "Sécurité",
  newPasswordPlaceholder: "NOUVEAU MOT DE PASSE",
  confirmPasswordPlaceholder: "CONFIRMER LE MOT DE PASSE",
  profileUpdated: "✅ Profil mis à jour !",
  saveErrorPrefix: "Erreur lors de l'enregistrement : ",
  slugMinLength: "⚠️ L'adresse unique (slug) doit contenir au moins 3 caractères.",
  slugTaken: "❌ Erreur : Le nom « {slug} » est déjà réservé par quelqu'un d'autre. Choisis une autre option.",
  slugSuccess: "✅ Félicitations ! Ton adresse unique a été réservée avec succès.",
  errorPrefix: "Erreur : ",
  passwordMismatch: "Les mots de passe ne correspondent pas !",
  passwordUpdated: "✅ Mot de passe mis à jour !",
  avatarErrorPrefix: "Erreur avatar : ",
  demoDisabled: "🔒 Désactivé en mode démo.",
  changeAvatar: "Changer",
  plans: {
    free: { nume: "CHRONOS FREE", limita: "30 réservations / mois" },
    pro: { nume: "CHRONOS PRO", limita: "150 réservations / mois" },
    elite: { nume: "CHRONOS ELITE", limita: "500 réservations / mois" },
    team: { nume: "CHRONOS TEAM", limita: "Réservations illimitées" }
  }
}},
de: { profil: {
  loading: "Profil wird synchronisiert...",
  demoMode: "VORSCHAUMODUS",
  idPrefix: "ID: ",
  defaultUser: "Chronos-Benutzer",
  save: "Speichern",
  saving: "Bitte warten...",
  logout: "Abmelden",
  demoLogout: "Demo beenden",
  activeSubscription: "Aktives Abo",
  trialSuffix: "(TESTPHASE)",
  changeSubscriptionBtn: "Abo ändern",
  fullNameLabel: "👤 Vollständiger Name",
  emailLabel: "✉️ E-Mail",
  phoneLabel: "📱 Telefon",
  roleLabel: "💼 Rolle / Funktion",
  publicLinkBadge: "Öffentlichen Link einrichten",
  slugLabel: "🔗 EINDEUTIGE BUCHUNGSADRESSE (SLUG)",
  slugPrefix: "/buchung/",
  slugPlaceholder: "unternehmensname",
  reserveLinkBtn: "Eindeutigen Link reservieren",
  checking: "Wird überprüft...",
  warningTitle: "⚠️ SEHR WICHTIG (PFLICHT):",
  warningText: "Diese Adresse (Slug) ist deine digitale Identität. Jede Änderung dieses Links macht automatisch bereits generierte QR-Codes und bereits an Kunden gesendete Links ungültig. Bitte wähle einen aussagekräftigen Namen (z. B. salon-art-nails), den du später nicht mehr änderst, um die Verbindung mit Kundenscans aktiv zu halten.",
  changePasswordBtn: "🔒 Zugangspasswort ändern",
  passwordModalTitle: "Sicherheit",
  newPasswordPlaceholder: "NEUES PASSWORT",
  confirmPasswordPlaceholder: "PASSWORT BESTÄTIGEN",
  profileUpdated: "✅ Profil aktualisiert!",
  saveErrorPrefix: "Fehler beim Speichern: ",
  slugMinLength: "⚠️ Die eindeutige Adresse (Slug) muss mindestens 3 Zeichen haben.",
  slugTaken: "❌ Fehler: Der Name „{slug}“ ist bereits von jemand anderem reserviert. Bitte wähle eine andere Option.",
  slugSuccess: "✅ Glückwunsch! Deine eindeutige Adresse wurde erfolgreich reserviert.",
  errorPrefix: "Fehler: ",
  passwordMismatch: "Passwörter stimmen nicht überein!",
  passwordUpdated: "✅ Passwort aktualisiert!",
  avatarErrorPrefix: "Avatar-Fehler: ",
  demoDisabled: "🔒 In der Demo deaktiviert.",
  changeAvatar: "Ändern",
  plans: {
    free: { nume: "CHRONOS FREE", limita: "30 Buchungen / Monat" },
    pro: { nume: "CHRONOS PRO", limita: "150 Buchungen / Monat" },
    elite: { nume: "CHRONOS ELITE", limita: "500 Buchungen / Monat" },
    team: { nume: "CHRONOS TEAM", limita: "Unbegrenzte Buchungen" }
  }
}},
es: { profil: {
  loading: "Sincronizando perfil...",
  demoMode: "MODO VISTA PREVIA",
  idPrefix: "ID: ",
  defaultUser: "Usuario Chronos",
  save: "Guardar",
  saving: "Espera...",
  logout: "Cerrar sesión",
  demoLogout: "Salir de la demo",
  activeSubscription: "Plan activo",
  trialSuffix: "(PRUEBA)",
  changeSubscriptionBtn: "Cambiar plan",
  fullNameLabel: "👤 Nombre completo",
  emailLabel: "✉️ Correo",
  phoneLabel: "📱 Teléfono",
  roleLabel: "💼 Rol / Función",
  publicLinkBadge: "Configuración de enlace público",
  slugLabel: "🔗 DIRECCIÓN ÚNICA DE RESERVA (SLUG)",
  slugPrefix: "/reserva/",
  slugPlaceholder: "nombre-negocio",
  reserveLinkBtn: "Reservar enlace único",
  checking: "Verificando...",
  warningTitle: "⚠️ MUY IMPORTANTE (OBLIGATORIO):",
  warningText: "Esta dirección (Slug) es tu identidad digital. Cualquier cambio en este enlace invalidará automáticamente los códigos QR generados anteriormente y los enlaces ya enviados a los clientes. Elige un nombre representativo (ej: salon-art-nails) que no cambies después, para mantener activa la conexión con los escaneos de los clientes.",
  changePasswordBtn: "🔒 Cambiar contraseña de acceso",
  passwordModalTitle: "Seguridad",
  newPasswordPlaceholder: "CONTRASEÑA NUEVA",
  confirmPasswordPlaceholder: "CONFIRMAR CONTRASEÑA",
  profileUpdated: "✅ ¡Perfil actualizado!",
  saveErrorPrefix: "Error al guardar: ",
  slugMinLength: "⚠️ La dirección única (slug) debe tener al menos 3 caracteres.",
  slugTaken: "❌ Error: El nombre \"{slug}\" ya está reservado por otra persona. Elige otra opción.",
  slugSuccess: "✅ ¡Felicidades! Tu dirección única se reservó con éxito.",
  errorPrefix: "Error: ",
  passwordMismatch: "¡Las contraseñas no coinciden!",
  passwordUpdated: "✅ ¡Contraseña actualizada!",
  avatarErrorPrefix: "Error de avatar: ",
  demoDisabled: "🔒 Desactivado en la demo.",
  changeAvatar: "Cambiar",
  plans: {
    free: { nume: "CHRONOS FREE", limita: "30 reservas / mes" },
    pro: { nume: "CHRONOS PRO", limita: "150 reservas / mes" },
    elite: { nume: "CHRONOS ELITE", limita: "500 reservas / mes" },
    team: { nume: "CHRONOS TEAM", limita: "Reservas ilimitadas" }
  }
}},
it: { profil: {
  loading: "Sincronizzazione profilo...",
  demoMode: "MODALITÀ ANTEPRIMA",
  idPrefix: "ID: ",
  defaultUser: "Utente Chronos",
  save: "Salva",
  saving: "Attendere...",
  logout: "Disconnetti",
  demoLogout: "Esci dalla demo",
  activeSubscription: "Piano attivo",
  trialSuffix: "(PROVA)",
  changeSubscriptionBtn: "Cambia piano",
  fullNameLabel: "👤 Nome completo",
  emailLabel: "✉️ Email",
  phoneLabel: "📱 Telefono",
  roleLabel: "💼 Ruolo / Funzione",
  publicLinkBadge: "Configurazione link pubblico",
  slugLabel: "🔗 INDIRIZZO UNICO DI PRENOTAZIONE (SLUG)",
  slugPrefix: "/prenotazione/",
  slugPlaceholder: "nome-attivita",
  reserveLinkBtn: "Riserva link unico",
  checking: "Verifica in corso...",
  warningTitle: "⚠️ MOLTO IMPORTANTE (OBBLIGATORIO):",
  warningText: "Questo indirizzo (Slug) è la tua identità digitale. Qualsiasi modifica a questo link invaliderà automaticamente i codici QR generati precedentemente e i link già inviati ai clienti. Scegli un nome rappresentativo (es: salon-art-nails) che non cambierai in seguito, per mantenere attiva la connessione con le scansioni dei clienti.",
  changePasswordBtn: "🔒 Cambia password di accesso",
  passwordModalTitle: "Sicurezza",
  newPasswordPlaceholder: "NUOVA PASSWORD",
  confirmPasswordPlaceholder: "CONFERMA PASSWORD",
  profileUpdated: "✅ Profilo aggiornato!",
  saveErrorPrefix: "Errore durante il salvataggio: ",
  slugMinLength: "⚠️ L'indirizzo unico (slug) deve contenere almeno 3 caratteri.",
  slugTaken: "❌ Errore: Il nome \"{slug}\" è già riservato da qualcun altro. Scegli un'altra opzione.",
  slugSuccess: "✅ Congratulazioni! Il tuo indirizzo unico è stato riservato con successo.",
  errorPrefix: "Errore: ",
  passwordMismatch: "Le password non coincidono!",
  passwordUpdated: "✅ Password aggiornata!",
  avatarErrorPrefix: "Errore avatar: ",
  demoDisabled: "🔒 Disattivato in modalità demo.",
  changeAvatar: "Cambia",
  plans: {
    free: { nume: "CHRONOS FREE", limita: "30 prenotazioni / mese" },
    pro: { nume: "CHRONOS PRO", limita: "150 prenotazioni / mese" },
    elite: { nume: "CHRONOS ELITE", limita: "500 prenotazioni / mese" },
    team: { nume: "CHRONOS TEAM", limita: "Prenotazioni illimitate" }
  }
}},
hu: { profil: {
  loading: "Profil szinkronizálása...",
  demoMode: "ELŐNÉZETI MÓD",
  idPrefix: "ID: ",
  defaultUser: "Chronos felhasználó",
  save: "Mentés",
  saving: "Kérlek várj...",
  logout: "Kijelentkezés",
  demoLogout: "Kilépés a demóból",
  activeSubscription: "Aktív csomag",
  trialSuffix: "(PRÓBA)",
  changeSubscriptionBtn: "Csomag módosítása",
  fullNameLabel: "👤 Teljes név",
  emailLabel: "✉️ E-mail",
  phoneLabel: "📱 Telefon",
  roleLabel: "💼 Szerep / Beosztás",
  publicLinkBadge: "Nyilvános link beállítása",
  slugLabel: "🔗 EGYEDI FOGLALÁSI CÍM (SLUG)",
  slugPrefix: "/foglalas/",
  slugPlaceholder: "vallalkozas-neve",
  reserveLinkBtn: "Egyedi link lefoglalása",
  checking: "Ellenőrzés...",
  warningTitle: "⚠️ NAGYON FONTOS (KÖTELEZŐ):",
  warningText: "Ez a cím (Slug) a digitális azonosítód. A link bármilyen módosítása automatikusan érvényteleníti a korábban generált QR-kódokat és az ügyfeleknek már elküldött linkeket. Válassz egy jellemző nevet (pl.: salon-art-nails), amelyet később nem változtatsz meg, hogy megmaradjon a kapcsolat az ügyfelek beolvasásaival.",
  changePasswordBtn: "🔒 Belépési jelszó módosítása",
  passwordModalTitle: "Biztonság",
  newPasswordPlaceholder: "ÚJ JELSZÓ",
  confirmPasswordPlaceholder: "JELSZÓ MEGERŐSÍTÉSE",
  profileUpdated: "✅ Profil frissítve!",
  saveErrorPrefix: "Hiba a mentés során: ",
  slugMinLength: "⚠️ Az egyedi címnek (slug) legalább 3 karakterből kell állnia.",
  slugTaken: "❌ Hiba: A \"{slug}\" nevet már más lefoglalta. Válassz másik lehetőséget.",
  slugSuccess: "✅ Gratulálunk! Az egyedi címedet sikeresen lefoglaltuk.",
  errorPrefix: "Hiba: ",
  passwordMismatch: "A jelszavak nem egyeznek!",
  passwordUpdated: "✅ Jelszó frissítve!",
  avatarErrorPrefix: "Avatar hiba: ",
  demoDisabled: "🔒 Letiltva a demóban.",
  changeAvatar: "Módosítás",
  plans: {
    free: { nume: "CHRONOS FREE", limita: "30 foglalás / hó" },
    pro: { nume: "CHRONOS PRO", limita: "150 foglalás / hó" },
    elite: { nume: "CHRONOS ELITE", limita: "500 foglalás / hó" },
    team: { nume: "CHRONOS TEAM", limita: "Korlátlan foglalás" }
  }
}},
pt: { profil: {
  loading: "A sincronizar perfil...",
  demoMode: "MODO DE PRÉ-VISUALIZAÇÃO",
  idPrefix: "ID: ",
  defaultUser: "Utilizador Chronos",
  save: "Guardar",
  saving: "Aguarda...",
  logout: "Terminar sessão",
  demoLogout: "Saída da Demo",
  activeSubscription: "Plano ativo",
  trialSuffix: "(TESTE)",
  changeSubscriptionBtn: "Alterar plano",
  fullNameLabel: "👤 Nome completo",
  emailLabel: "✉️ Email",
  phoneLabel: "📱 Telefone",
  roleLabel: "💼 Função / Cargo",
  publicLinkBadge: "Configuração do link público",
  slugLabel: "🔗 ENDEREÇO ÚNICO DE MARCAÇÃO (SLUG)",
  slugPrefix: "/marcacao/",
  slugPlaceholder: "nome-negocio",
  reserveLinkBtn: "Reservar link único",
  checking: "A verificar...",
  warningTitle: "⚠️ MUITO IMPORTANTE (OBRIGATÓRIO):",
  warningText: "Este endereço (Slug) é a tua identidade digital. Qualquer alteração a este link invalidará automaticamente os Códigos QR gerados anteriormente e os links já enviados aos clientes. Escolhe um nome representativo (ex: salon-art-nails) que não vás alterar depois, para manter a ligação ativa com os scans dos clientes.",
  changePasswordBtn: "🔒 Alterar palavra-passe de acesso",
  passwordModalTitle: "Segurança",
  newPasswordPlaceholder: "NOVA PALAVRA-PASSE",
  confirmPasswordPlaceholder: "CONFIRMAR PALAVRA-PASSE",
  profileUpdated: "✅ Perfil atualizado!",
  saveErrorPrefix: "Erro ao guardar: ",
  slugMinLength: "⚠️ O endereço único (slug) deve ter pelo menos 3 caracteres.",
  slugTaken: "❌ Erro: O nome \"{slug}\" já está reservado por outra pessoa. Escolhe outra opção.",
  slugSuccess: "✅ Parabéns! O teu endereço único foi reservado com sucesso.",
  errorPrefix: "Erro: ",
  passwordMismatch: "As palavras-passe não coincidem!",
  passwordUpdated: "✅ Palavra-passe atualizada!",
  avatarErrorPrefix: "Erro de avatar: ",
  demoDisabled: "🔒 Desativado na demo.",
  changeAvatar: "Alterar",
  plans: {
    free: { nume: "CHRONOS FREE", limita: "30 marcações / mês" },
    pro: { nume: "CHRONOS PRO", limita: "150 marcações / mês" },
    elite: { nume: "CHRONOS ELITE", limita: "500 marcações / mês" },
    team: { nume: "CHRONOS TEAM", limita: "Marcações ilimitadas" }
  }
}},
pl: { profil: {
  loading: "Synchronizacja profilu...",
  demoMode: "TRYB PODGLĄDU",
  idPrefix: "ID: ",
  defaultUser: "Użytkownik Chronos",
  save: "Zapisz",
  saving: "Czekaj...",
  logout: "Wyloguj się",
  demoLogout: "Wyjdź z demo",
  activeSubscription: "Aktywny plan",
  trialSuffix: "(PRÓBA)",
  changeSubscriptionBtn: "Zmień plan",
  fullNameLabel: "👤 Imię i nazwisko",
  emailLabel: "✉️ Email",
  phoneLabel: "📱 Telefon",
  roleLabel: "💼 Rola / Funkcja",
  publicLinkBadge: "Konfiguracja publicznego linku",
  slugLabel: "🔗 UNIKALNY ADRES REZERWACJI (SLUG)",
  slugPrefix: "/rezerwacja/",
  slugPlaceholder: "nazwa-firmy",
  reserveLinkBtn: "Zarezerwuj unikalny link",
  checking: "Sprawdzanie...",
  warningTitle: "⚠️ BARDZO WAŻNE (WYMAGANE):",
  warningText: "Ten adres (Slug) to Twoja cyfrowa tożsamość. Jakakolwiek zmiana tego linku automatycznie unieważni wcześniej wygenerowane kody QR i linki już wysłane klientom. Wybierz reprezentatywną nazwę (np. salon-art-nails), której nie zmienisz później, aby zachować aktywne połączenie ze skanami klientów.",
  changePasswordBtn: "🔒 Zmień hasło dostępu",
  passwordModalTitle: "Bezpieczeństwo",
  newPasswordPlaceholder: "NOWE HASŁO",
  confirmPasswordPlaceholder: "POTWIERDŹ HASŁO",
  profileUpdated: "✅ Profil zaktualizowany!",
  saveErrorPrefix: "Błąd podczas zapisywania: ",
  slugMinLength: "⚠️ Unikalny adres (slug) musi mieć co najmniej 3 znaki.",
  slugTaken: "❌ Błąd: Nazwa \"{slug}\" jest już zarezerwowana przez kogoś innego. Wybierz inną opcję.",
  slugSuccess: "✅ Gratulacje! Twój unikalny adres został pomyślnie zarezerwowany.",
  errorPrefix: "Błąd: ",
  passwordMismatch: "Hasła nie są zgodne!",
  passwordUpdated: "✅ Hasło zaktualizowane!",
  avatarErrorPrefix: "Błąd awatara: ",
  demoDisabled: "🔒 Wyłączone w wersji demo.",
  changeAvatar: "Zmień",
  plans: {
    free: { nume: "CHRONOS FREE", limita: "30 rezerwacji / mies." },
    pro: { nume: "CHRONOS PRO", limita: "150 rezerwacji / mies." },
    elite: { nume: "CHRONOS ELITE", limita: "500 rezerwacji / mies." },
    team: { nume: "CHRONOS TEAM", limita: "Nieograniczone rezerwacje" }
  }
}}
};

const messagesDir = path.join(__dirname, "messages");
for (const locale of Object.keys(DATA)) {
  const filePath = path.join(messagesDir, `${locale}.json`);
  if (!fs.existsSync(filePath)) { console.log(`⚠️  Nu găsesc ${filePath}`); continue; }
  const json = JSON.parse(fs.readFileSync(filePath, "utf8"));
  Object.assign(json, DATA[locale]);
  fs.writeFileSync(filePath, JSON.stringify(json, null, 2), "utf8");
  console.log(`✅ ${locale}.json actualizat (profil).`);
}
console.log("\n🎉 Traducerile pentru profil au fost adăugate!");